apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: k29h6vfyn-java-quarkus
  janus-idp.io/tekton: k29h6vfyn-java-quarkus
  backstage.io/kubernetes-id: k29h6vfyn-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: k29h6vfyn-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
